name: Import BRaft Actions (Temporary)

on:
  push:
  pull_request:
    branches: [ "import-braft" ]

jobs:
  check_format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: bash ci/build.sh

      - name: Check Format
        working-directory: ${{ github.workspace }}/build
        run: make check-format

  build_on_macos:
    runs-on: macos-latest
    needs: check_format

    steps:
      - uses: actions/checkout@v4

      - name: Build
        env: 
          CPLUS_INCLUDE_PATH: /opt/homebrew/include
        run: |
          brew install autoconf
          brew install go
          sh build.sh

      - name: Run Go E2E Tests
        working-directory: ${{ github.workspace }}/build-release
        run: |
          cd ../tests
          go mod tidy
          go test ./pikiwidb_suite_test.go ./consistency_test.go -v

  build_on_ubuntu:
    runs-on: ubuntu-latest
    needs: check_format

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          bash build.sh

      - name: Run Go E2E Tests
        working-directory: ${{ github.workspace }}/build-release
        run: |
          cd ../tests
          go mod tidy
          go test ./pikiwidb_suite_test.go ./consistency_test.go -v
